### ISSUE TITLE
Transcode failure with long files

### ISSUE THREAD

**Issue by PsychedelicGhost** [kokorin/Jaffree#47] opened 2019-04-08 16:00 UTC
My use case is transcoding an hour long audio file (wav to aac) using PipeOutput.

` FFmpeg.atPath(Paths.get(ffmpegBinDirectory))
            .addInput(PipeInput.pumpFrom(input))
            .addOutput(PipeOutput.pumpTo(output).setFormat("mp4"))
            .addArguments("-movflags", "frag_keyframe+faststart")
            .addArguments("-c:a", "aac")
            .execute();`

The file is totally unplayable when using PipeOutput, however if I use UrlOutput then the file is playable.

**Comment by kokorin** [comment] 2019-04-08 16:10
Please, provide sample project with sample file for reproduction.

пн, 8 апр. 2019, 19:00 PsychedelicGhost <notifications@github.com>:

**Comment by PsychedelicGhost** [comment] 2019-04-08 16:41
[encoding.zip](https://github.com/kokorin/Jaffree/files/3055372/encoding.zip)

**Comment by PsychedelicGhost** [comment] 2019-04-08 16:47
[encoding.zip](https://github.com/kokorin/Jaffree/files/3055406/encoding.zip)

**Comment by PsychedelicGhost** [comment] 2019-04-08 16:47
Sample project with hour long wav file in resources, adjust to suit your ffmpeg bin location

**Comment by kokorin** [comment] 2019-04-08 16:51
Sure, thank you, will check asap

пн, 8 апр. 2019, 19:48 PsychedelicGhost <notifications@github.com>:

**Comment by PsychedelicGhost** [comment] 2019-04-08 17:10
aac file size differs when saving as file / saving as a stream

change output codec to:-

wav: duration is about 36 hours
mp3: duration is reported differently in (VLC, Chrome, IE)

Perhaps ffmpeg is trying to seek back to the start of the stream and fails to do so.

**Comment by kokorin** [comment] 2019-04-13 04:34
@PsychedelicGhost I have checked your sample project. Unfortunately I wasn't able to fix it with PipeOutput. 
Strange because PipeOutput produces correct MP4 (without seeking of course) when concat input format and copy codec are used.

Also I noticed that you don't close OutputStream in sample project.

Closing this issue, since it doesn't relate to Jaffree itself

**Closed by kokorin** 2019-04-13 04:34 UTC

**Comment by kokorin** [comment] 2019-07-27 10:03
@PsychedelicGhost not sure if this is still relevant to you, but I have added ChannelInput & ChannelOutput to Jaffree 0.9.0.  So now you can you ChannelOutput to produce correct WAV or MP3.

**Comment by PsychedelicGhost** [comment] 2019-07-29 08:20
@kokorin This is still relevant, thank you for addressing this. I will update and integrate the changes, hopefully that will limit the amount of data I write to disk between transcoding attempts
