### ISSUE TITLE
[QUESTION] How include an optional data input

### ISSUE THREAD

**Issue by dyorgio** [kokorin/Jaffree#50] opened 2019-07-17 12:56 UTC
Hi @kokorin, tks for this amazing library!
I'm using it to create a dynamic generator video/sound streamer:

```.java
public FFmpegResult startAndWait() throws IOException {
        FFmpeg ffmpeg = FFmpeg.atPath(Paths.get(System.getProperty("natives.ffmpeg.path"))) //
                .addInput(FrameInput.withProducer(new VideoProducer()).setFrameRate(framerate).setReadAtFrameRate(true)) //
                .addInput(FrameInput.withProducer(new AudioProducer()).setFrameRate(framerate).setReadAtFrameRate(true)) //
                .addOutput(//
                        UrlOutput.toUrl("udp://127.0.0.1:14667?pkt_size=1316")//
                                .setPixelFormat("yuv420p")//
                                .setFrameRate(framerate)//
                                .addArguments("-preset", "ultrafast")//
                                .addArguments("-tune", "zerolatency")//
                                .addArguments("-b", "900k")
                                .addArguments("-g", String.valueOf(2 * framerate))//
                                .setCodec(StreamType.VIDEO, OSDetector.isMac() ? "h264_videotoolbox" : "libx264")//
                                .setFormat("mpegts")//
                );

        return ffmpeg.execute();
    }
```

This code is working fine, I can consume it on VLC with address udp://@:14667 without drop frames and with good quality of video and sound :), thank you again \o/ \o/ \o/.

But I can't make a "dynamic" input work, let me explain my idea:

If I include a new UDP input, like:
```.java
addInput(UrlInput.fromUrl("udp://localhost:14666"))
```

And after that I create another instance of ffmpeg with output to this address (external source):
```.java
FFmpeg ffmpeg = FFmpeg.atPath(Paths.get(System.getProperty("natives.ffmpeg.path"))) //
        .addInput(UrlInput.fromPath(Paths.get("./sound.mp3")).setReadAtFrameRate(true)) //
        .addOutput(//
                UrlOutput.toUrl("udp://127.0.0.1:14666?pkt_size=1316")//
                        .addArguments("-tune", "zerolatency")//
                        .setFrameRate(25)
                        .setFormat("mpegts")//
        );

ffmpeg.execute();
```

The resulting of first ffmpeg drops a lot of frames, delay some seconds to show first frame and play only some parts of external sound (sound.mp3).

My question: Can ffmpeg "ignore" no data on an input? Or... Can I tell to ffmpeg to don't use this input if no data (bytes received) and only use it if data is present? (better if input fps is ignored too).

**Comment by kokorin** [comment] 2019-07-17 14:14
Hello Dyorgio Nasciment,

Actually I haven't fully understood what you mean, but I can recommend to
check the following option of ffmpeg UDP protocol:

connect=1|0
>
> Initialize the UDP socket with connect(). In this case, the destination
> address can’t be changed with ff_udp_set_remote_url later. If the
> destination address isn’t known at the start, this option can be specified
> in ff_udp_set_remote_url, too. This allows finding out the source address
> for the packets with getsockname, and makes writes return with
> AVERROR(ECONNREFUSED) if "destination unreachable" is received. For
> receiving, this gives the benefit of only receiving packets from the
> specified peer address/port.
>
Also AFAIK UDP doesn't guarantee delivery, so this also may be a reason to
your problem.

And of course it's hard to reproduce without having sample project.

Best regards,
Denis Kokorin

**Comment by dyorgio** [comment] 2019-07-17 17:13
Didn't work :(.

In resume I need to "ignore" a input if it don't have data, and use it if data became available.
My idea is "prepare" a instance of ffmpeg to receive media in any time:

```.java
.addInput(UrlInput.fromUrl("udp://localhost:14001")) //Track 1
.addInput(UrlInput.fromUrl("udp://localhost:14002")) //Track 2
.addInput(UrlInput.fromUrl("udp://localhost:14003")) //Track 3
.addInput(UrlInput.fromUrl("udp://localhost:14004")) //Track 4
.addInput(UrlInput.fromUrl("udp://localhost:14005")) //Track 5
.addInput(UrlInput.fromUrl("udp://localhost:14006")) //Track 6
// Tracks 7...99
.addInput(UrlInput.fromUrl("udp://localhost:14100")) //Track 100
```

I attached an example that, if you dont remove udp input (second), no video is available, removing it, frames are generated normally.

That do you think? is it possible with ffmpeg?

[StreamerTest.java.zip](https://github.com/kokorin/Jaffree/files/3402981/StreamerTest.java.zip)

**Comment by dyorgio** [comment] 2019-07-18 01:27
Hello @kokorin, I gave up to try to ignore input, appears to be impossible in ffmpeg:

[https://video.stackexchange.com/questions/14502/how-to-display-static-image-if-the-input-stream-ends-using-ffmpeg/20743#20743](https://video.stackexchange.com/questions/14502/how-to-display-static-image-if-the-input-stream-ends-using-ffmpeg/20743#20743)

So I decided to make a bridge in pure Java 😅 :

```.java
private class DynamicAudioBridge implements FrameProducer, FrameConsumer {

        private long frameCounter = 0;
        private boolean cleaned = false;
        private int[] buffer;
        // EvictingQueue from guava
        private final EvictingQueue<Frame> queue;

        public DynamicAudioBridge(int queueSize) {
            this.queue = EvictingQueue.create(queueSize);
        }

        @Override
        public List<Stream> produceStreams() {
            return Arrays.asList(
                    new Stream().setId(0).setType(Type.AUDIO)
                            .setChannels(2)
                            .setTimebase(44100l)
                            .setSampleRate(44100l)
            );
        }

        @Override
        public Frame produce() {
            Frame frame = queue.poll();
            if (frame != null) {
                // use queue frame buffer
                buffer = frame.getSamples();
                cleaned = false;
            } else if (!cleaned) {
                buffer = new int[32];
                cleaned = true;
            }
            frameCounter += (buffer.length / 2);
            return new Frame(0, frameCounter, buffer);
        }

        @Override
        public void consumeStreams(List<Stream> streams) {
            // nothing for while
        }

        @Override
        public void consume(Frame frame) {
            if (frame != null) {
                // put on queue
                audioBridge.queue.offer(frame);
            }
        }
    }
```

It works like a charm!
The idea is produce "empty" frame if queue is empty, and feed queue with another ffmpeg instance:

```.java
public Future<FFmpegResult> playAudio(String url) {
        FFmpeg ffmpeg = FFmpeg.atPath(Paths.get(System.getProperty("natives.ffmpeg.path"))) //
                // ReadAtFrameRate = true to don't read entire file in memory
                .addInput(UrlInput.fromUrl(url).setFrameRate(framerate).setReadAtFrameRate(true)) // 
                .addOutput(FrameOutput.withConsumer(audioBridge).disableStream(StreamType.VIDEO) //
                );

        return ffmpeg.executeAsync();
    }
```

Sharing as open source if you think it is a good add to this library.

**Comment by kokorin** [comment] 2019-07-18 04:36
@dyorgio you definitely need some relay to switch between incoming UDP and produced streams. 
Actually I'm not an expert in ffmpeg, the only I can recommend to play with ffmpeg filter fraph to check if it's possible to switch with it between input streams.
Also notice that FrameInput/FrameOutput require encoding/decoding, so you may have performance problem with live streams with HD video.

Anyway, glad you find Jaffree useful.

Closing this ticket, since the problem is solved.

**Closed by kokorin** 2019-07-18 04:36 UTC
